import type { SettingsCenterSettings } from "../contracts/settings-center-settings";

export const SETTINGS_CENTER_TEST_SETTINGS: SettingsCenterSettings = {
	revision: 0,
	general: {
		interfaceLanguage: "en-US",
		editingMode: "live-preview",
		showLineNumbers: true,
		statusBarMode: "detailed",
		autoSave: true,
		autoSaveInterval: "30",
		syncScroll: true,
		publishVisibility: "public",
		openPreviewAfterPublish: true,
		applyEditorThemeToFrontend: true,
		showPublishedCodeCopyButton: true,
		summaryMode: "auto-55",
	},
	images: {
		imageHostingEnabled: false,
		wechatPngExportEnabled: false,
		service: "cloudflare-r2",
		endpoint:
			"https://0123456789abcdef0123456789abcdef.r2.cloudflarestorage.com",
		bucket: "easymde-assets",
		domain: "",
		accessKey: "",
		secretKey: "",
		fileNameRule: "{year}/{month}/{md5}.{ext}",
		uploadRetryCount: 0,
		backupEnabled: true,
		backupService: "qiniu-kodo",
		backupEndpoint: "",
		backupBucket: "easymde-backup",
		backupDomain: "",
		backupAccessKey: "",
		backupSecretKey: "",
		compressImages: true,
		autoUploadPastedImages: true,
		remoteImageUploadMode: "both",
		maxImageSizeMb: 5,
		uploadFormats: { jpg: true, png: true, webp: true, gif: true },
		titleDisplay: "none",
	},
	markdown: {
		wordWrap: true,
		githubFlavor: true,
		smartPunctuation: true,
		tableAlignment: "center",
		codeLineNumbers: "show",
		pasteAsMarkdown: true,
	},
	shortcuts: {
		values: {
			save: { windows: "Ctrl+S", mac: "Cmd+S" },
			bold: { windows: "Ctrl+B", mac: "Cmd+B" },
			italic: { windows: "Ctrl+I", mac: "Cmd+I" },
			strikethrough: { windows: "Alt+Shift+5", mac: "Ctrl+Shift+Backquote" },
			paragraph: { windows: "Ctrl+0", mac: "Cmd+0" },
			link: { windows: "Ctrl+K", mac: "Cmd+K" },
			image: { windows: "Ctrl+Shift+I", mac: "Cmd+Ctrl+I" },
			"heading-one": { windows: "Ctrl+1", mac: "Cmd+1" },
			"heading-two": { windows: "Ctrl+2", mac: "Cmd+2" },
			"heading-three": { windows: "Ctrl+3", mac: "Cmd+3" },
			"heading-four": { windows: "Ctrl+4", mac: "Cmd+4" },
			"heading-five": { windows: "Ctrl+5", mac: "Cmd+5" },
			"heading-six": { windows: "Ctrl+6", mac: "Cmd+6" },
			quote: { windows: "Ctrl+Shift+Q", mac: "Cmd+Option+Q" },
			"unordered-list": {
				windows: "Ctrl+Shift+BracketRight",
				mac: "Cmd+Option+U",
			},
			"ordered-list": {
				windows: "Ctrl+Shift+BracketLeft",
				mac: "Cmd+Option+O",
			},
			"inline-code": {
				windows: "Ctrl+Shift+Backquote",
				mac: "Cmd+Shift+Backquote",
			},
			"code-fence": { windows: "Ctrl+Shift+K", mac: "Cmd+Option+C" },
			"math-block": { windows: "Ctrl+Shift+M", mac: "Cmd+Option+B" },
		},
	},
};
export const SETTINGS_CENTER_DEFAULT_SETTINGS: SettingsCenterSettings = {
	...SETTINGS_CENTER_TEST_SETTINGS,
	revision: 0,
};
